name: PMON Compile CI

on:
  # push:
  # pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt-get install -y flex bison xutils-dev
    - name: Download toolchain
      run: wget -O /tmp/gcc-4.4.0-pmon.tgz https://mirrors.ustc.edu.cn/loongson/loongson1c_bsp/gcc-4.3/gcc-4.3-ls232.tar.gz 
    - name: Install toolchain
      run: sudo tar -zxvf /tmp/gcc-4.4.0-pmon.tgz -C /opt/

    - name: Compile and install pmoncfg
      run: cd tools/pmoncfg && make && sudo cp pmoncfg /opt/gcc-4.3-ls232/bin/

    - name: Setup env
      run: echo "/opt/gcc-4.3-ls232/bin" >> $GITHUB_PATH && echo "LD_LIBRARY_PATH=/opt/gcc-4.3-ls232/lib" >> $GITHUB_ENV && mkdir output

    - name: Compile 2edev
      run: cd zloader.2edev && make cfg && make tgt=rom && cd ..
    - name: Collect 2edev
      run: cp zloader/gzrom.bin output/pmon-2edev.bin && md5sum output/pmon-2edev.bin > output/pmon-2edev.bin.md5

    - name: Compile ls2k-pi2
      run: cd zloader.ls2k-pi2 && make cfg && make tgt=rom && make dtb && cd ..
    - name: Collect ls2k-pi2
      run: cp zloader/gzrom-dtb.bin output/pmon-ls2k-pi2.bin && md5sum output/pmon-ls2k-pi2.bin > output/pmon-ls2k-pi2.bin.md5

    - name: Compile ls2k-edu
      run: cd zloader.ls2k-edu && make cfg && make tgt=rom && make dtb && cd ..
    - name: Collect ls2k-edu
      run: cp zloader/gzrom-dtb.bin output/pmon-ls2k-edu.bin && md5sum output/pmon-ls2k-edu.bin > output/pmon-ls2k-edu.bin.md5

    - name: Compile 3avirt
      run: cd zloader.3avirt && make cfg && make tgt=rom && cd ..
    - name: Collect 3avirt
      run: cp zloader/gzrom.bin output/pmon-3avirt.bin && md5sum output/pmon-3avirt.bin > output/pmon-3avirt.bin.md5

    - name: Compile lm-a1901
      run: cd zloader.lm-a1901 && make cfg && make tgt=rom && cd ..
    - name: Collect lm-a1901
      run: cp zloader/gzrom.bin output/pmon-lm-a1901.bin && md5sum output/pmon-lm-a1901.bin > output/pmon-lm-a1901.bin.md5

    - name: Upload outputs
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output/